spring.application.name=apptrack
spring.datasource.url=jdbc:postgresql://localhost:5432/apptrack
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true