CREATE TABLE public.applications (
    active boolean NOT NULL,
    date_final_round date,
    date_offer date,
    date_recruiter_call date,
    date_recruiter_response date,
    date_rejection date,
    date_submitted date,
    date_technical_pass date,
    date_technical_screen date,
    referred boolean NOT NULL,
    contact_id bigint,
    id bigint NOT NULL,
    job_listing_id bigint NOT NULL,
    resume_variant_id bigint NOT NULL,
    alignment_notes character varying(255),
    current_stage character varying(255),
    notes character varying(255),
    rejection_stage character varying(255),
    source_channel character varying(255),
    CONSTRAINT applications_current_stage_check CHECK (((current_stage)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'RECRUITER_RESPONSE'::character varying, 'RECRUITER_CALL'::character varying, 'TECHNICAL_SCREEN'::character varying, 'TECHNICAL_PASS'::character varying, 'FINAL_ROUND'::character varying, 'OFFER'::character varying, 'REJECTED'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT applications_source_channel_check CHECK (((source_channel)::text = ANY ((ARRAY['COLD'::character varying, 'REFERRAL'::character varying, 'RECRUITER_OUTREACH'::character varying, 'JOB_BOARD'::character varying])::text[])))
);


--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    notes text,
    segment character varying(255) NOT NULL,
    size character varying(255),
    CONSTRAINT companies_segment_check CHECK (((segment)::text = ANY ((ARRAY['DEFENSE'::character varying, 'EDUCATION'::character varying, 'ENTERPRISE'::character varying, 'CONSULTING'::character varying, 'FINANCE'::character varying, 'HEALTHCARE'::character varying, 'FINTECH'::character varying, 'TECH'::character varying, 'STARTUP'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT companies_size_check CHECK (((size)::text = ANY ((ARRAY['SMALL'::character varying, 'MEDIUM'::character varying, 'LARGE'::character varying])::text[])))
);


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contacts (
    id bigint NOT NULL,
    company character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    notes text,
    phone character varying(255)
);


--
-- Name: contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: joblistings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.joblistings (
    date_discovered date,
    date_expired date,
    company_id bigint,
    id bigint NOT NULL,
    description_notes text,
    domain_notes character varying(255),
    experience_level character varying(255),
    role_type character varying(255),
    title character varying(255),
    url character varying(255),
    CONSTRAINT joblistings_experience_level_check CHECK (((experience_level)::text = ANY ((ARRAY['JUNIOR'::character varying, 'MID'::character varying, 'SENIOR'::character varying])::text[]))),
    CONSTRAINT joblistings_role_type_check CHECK (((role_type)::text = ANY ((ARRAY['BACKEND'::character varying, 'FULLSTACK'::character varying, 'PLATFORM'::character varying, 'DEVOPS'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: joblistings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.joblistings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.joblistings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pipelineevents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pipelineevents (
    occurrence_index integer NOT NULL,
    application_id bigint NOT NULL,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone,
    event_type character varying(255),
    from_stage character varying(255),
    notes character varying(255),
    to_stage character varying(255)
);


--
-- Name: pipelineevents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pipelineevents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipelineevents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: qualitativetags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.qualitativetags (
    date date,
    application_id bigint,
    id bigint NOT NULL,
    pipelineevent_id bigint,
    notes text,
    sentiment character varying(255),
    tag_text character varying(255),
    CONSTRAINT qualitativetags_sentiment_check CHECK (((sentiment)::text = ANY ((ARRAY['POSITIVE'::character varying, 'NEUTRAL'::character varying, 'NEGATIVE'::character varying])::text[])))
);


--
-- Name: qualitativetags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.qualitativetags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.qualitativetags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resumevariants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resumevariants (
    date_created date,
    id bigint NOT NULL,
    change_summary character varying(255),
    file_url character varying(255),
    version_label character varying(255) NOT NULL
);


--
-- Name: resumevariants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resumevariants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resumevariants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: joblistings joblistings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.joblistings
    ADD CONSTRAINT joblistings_pkey PRIMARY KEY (id);


--
-- Name: pipelineevents pipelineevents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipelineevents
    ADD CONSTRAINT pipelineevents_pkey PRIMARY KEY (id);


--
-- Name: qualitativetags qualitativetags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qualitativetags
    ADD CONSTRAINT qualitativetags_pkey PRIMARY KEY (id);


--
-- Name: resumevariants resumevariants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resumevariants
    ADD CONSTRAINT resumevariants_pkey PRIMARY KEY (id);


--
-- Name: pipelineevents fk3jdadiy73mhl85w6848lk58h4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pipelineevents
    ADD CONSTRAINT fk3jdadiy73mhl85w6848lk58h4 FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: joblistings fk6bhtagmksik2f2q63623h3obk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.joblistings
    ADD CONSTRAINT fk6bhtagmksik2f2q63623h3obk FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- Name: applications fk6r9r6p6b9yd4stcdjqu6ijq31; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fk6r9r6p6b9yd4stcdjqu6ijq31 FOREIGN KEY (job_listing_id) REFERENCES public.joblistings(id);


--
-- Name: applications fkbixechssbpkayw1mkoj8yvmq4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkbixechssbpkayw1mkoj8yvmq4 FOREIGN KEY (resume_variant_id) REFERENCES public.resumevariants(id);


--
-- Name: applications fkbnghx54k5scqjij4oq3hfghcw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkbnghx54k5scqjij4oq3hfghcw FOREIGN KEY (contact_id) REFERENCES public.contacts(id);


--
-- Name: qualitativetags fkhbmwgadj857rxpxxnq07c9dlq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qualitativetags
    ADD CONSTRAINT fkhbmwgadj857rxpxxnq07c9dlq FOREIGN KEY (pipelineevent_id) REFERENCES public.pipelineevents(id);


--
-- Name: qualitativetags fkrs165ndtba4nbj2nicqoamw24; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.qualitativetags
    ADD CONSTRAINT fkrs165ndtba4nbj2nicqoamw24 FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- PostgreSQL database dump complete
--

